spring:
  config.import: "configserver:"
  application:
    name: edge-server
  cloud:
    config:
      failFast: true
      uri: http://config-server:8888
      username: ${CONFIG_SERVER_USER}
      password: ${CONFIG_SERVER_PASSWORD}
  profiles:
    active: docker

server:
  port: 8080  # fallback si config-server no estuviera disponible
  #para https
  ssl:
    enabled: true
    key-store: classpath:gateway.p12
    key-store-password: ${SSL_KEYSTORE_PASSWORD}
    key-store-type: PKCS12
    key-alias: gateway-cert
